version: '3.4'

services:
  octo_events:
    image: octo_events
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - .:/home/octo_events
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: not_a_prod_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
volumes:
  db_data:
